title: Winnie Liu # your name (or website title) here
logo: "/images/profilepic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master Student @ UPenn Computer Science |Data Analyst | UW MSIS 2020
  <br><br>
  Front End Developer| Full Stack
  React |JavaScript |HTML |CSS |Bootstrap
  <br><br>
  <a href="https://www.linkedin.com/in/jingyi-winnie-liu-8327a8101/">View My LinkedIn Profile</a> 
  <a href="https://https://github.com/ljy19971022">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
