title: Winnie Liu # your name (or website title) here
logo: "/images/profilepic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master Student @ UPenn Computer Science | UW MSIS 2020
  <br><br>
  |Front End |Full Stack |Data Analyst
  <br><br>
  Java |Python |React |Mern Stack|JavaScript |HTML |CSS |Bootstrap|SQL |Tableau
  <br><br>
  <a href="https://www.linkedin.com/in/jingyi-winnie-liu-8327a8101/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
